apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.form: ""
  name: 'app-2'
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: performance
  source:
    repoURL: 'https://github.com/JuanmaBM/argocd-webhook-poc'
    path: performance/gitops/hello-api
    targetRevision: HEAD
  sources: []
  project: 'default'
  syncPolicy:
    automated: {}