apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'app-1'
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: performance
  source:
    repoURL: 'https://github.com/JuanmaBM/argocd-webhook-poc'
    path: performance/gitops/go-toolset
    targetRevision: HEAD
  sources: []
  project: 'default'
  syncPolicy:
    automated: {}