apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  selector:
    matchLabels:
      app: service-a
  replicas: 2
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: nginx:latest
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   runAsNonRoot: true
        #   seccompProfile:
        #     type: RuntimeDefault
        #   capabilities:
        #     drop:
        #     - ALL
        ports:
        - containerPort: 80
