apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   runAsNonRoot: true
        #   seccompProfile:
        #     type: RuntimeDefault
        #   capabilities:
        #     drop:
        #     - ALL
        ports:
        - containerPort: 80
