apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-event-subscriptor
spec:
  selector:
    matchLabels:
      app: argocd-event-subscriptor
  replicas: 1
  template:
    metadata:
      labels:
        app: argocd-event-subscriptor
    spec:
      containers:
      - name: argocd-event-subscriptor
        image: quay.io/juanmabm/argocd-event-subscriptor:1.1
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   runAsNonRoot: true
        #   seccompProfile:
        #     type: RuntimeDefault
        #   capabilities:
        #     drop:
        #     - ALL
        ports:
        - containerPort: 8080
