apiVersion: v1
kind: Service
metadata:
  name: argocd-event-subscriptor
spec:
  selector:
    app: argocd-event-subscriptor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
